jobs:
     tests:
         name: Testes Robot Framework
         runs-on: ubuntu-24.04
 
         steps:
           - name: Clonando o projeto para a maquina virtual
             uses: actions/checkout@v4
 
           - name: Configurando o Python na maquina virtual
             uses: actions/setup-python@v5
 
           - name: Instalação das dependencias
             run: |            
               pip install robotframework
               pip install robotframework-requests
 
           - name: Executando os testes
             run: |
               robot --outputdir results/ .
 
           - name: Resultado dos Testes
             uses: actions/upload-artifact@v4
             if: always()
             with:
                 name: resultado-testes
                 path: results